### ISSUE TITLE
无法获取数据

### ISSUE THREAD

**Issue by IsQiao** [logerror/coin-to-the-moon#3]
![image](https://user-images.githubusercontent.com/8536046/134613612-a4b34574-8b50-42a2-80ac-120ac56f6d40.png)

**Comment by logerror** [comment]
不好意思，刚看到，我看了下由于我在代码中是用非小号的api获取数据的，目前这个api好像访问不通了

**Comment by logerror** [comment]
有兴趣的话可以考虑换一个api来实现

**Comment by logerror** [comment]
修复了这个问题在 1.1.0版本，目前正在审核

**Comment by logerror** [comment]
更新了 1.1.2 版本
